export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const SIGNIN_ATTEMPT = 'LOGIN_ATTEMPT';
export const SIGNIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const SIGNIN_USER_FAIL = 'LOGIN_USER_FAIL';
